### ISSUE TITLE
Has an alternative been found?

### ISSUE THREAD

**Issue by ciaransweet** [iann0036/cfn-leastprivilege#3]
Hi @iann0036 

This tool looks really promising and just the kind of thing I've been looking for.

My use case is that I'm deploying infrastructure within CircleCI builds and I want to give the IAM User for the agents a lot less than full admin access 🤣 

I've noticed the repo has been quiet for a fair few months - do you have an alternative to use now?

I would love to hear any experience you've got in least privileged exploration!

**Comment by iann0036** [comment]
Hey @ciaranevans,

Thanks for reaching out. Unfortunately, the sheer scope of this project meant I couldn't continue on - at least going in on as fine detail as I wanted to.

In the end, I think it's important to understand that many things require a level of access that is as good as administrative privileges themselves (read: iam:CreateRole, iam:PassRole). A strong permission boundary on your users group and enforced SCPs are among the best tools available in this space, so I would encourage you to look further into these before going full insanity like I have attempted here.

**Comment by ciaransweet** [comment]
Cool thanks for the really prompt reply @iann0036, haha it is indeed a very daunting scope! 

I'll take a look into SCPs, currently it's a pretty small(?) org/project so we're pretty cognisant of what we've got. Just looking around for small wins on restricting services!

Appreciate the pointers!
